version: "2"

networks:
  space:
    external: false

services:
  phoenix:
    build: backend
    restart: unless-stopped
    networks:
      - space
    depends_on:
      - db

  gephi:
    build: gephi

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - space
    volumes:
      - /var/lib/postgresql/data

  elastic:
    image: elasticsearch:8.7.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    networks: 
      - space
