version: '3'
services:
  db:
    restart: always
    networks:
      - database_network
  django:
    restart: always
    volumes:
      - ./config/gunicorn.conf.py:/config/gunicorn.conf.py
      - gunicorn-socket:/var/gunicorn
      - staticfiles:/code/backend/static
    networks:
      - database_network
      - server_network
    environment:
      - ENVIRONMENT=production
      - DJANGO_SETTINGS_MODULE=backend.settings.production
  caddy:
    restart: always
    image: abiosoft/caddy:0.11.4-no-stats
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - staticfiles:/srv/static
      - caddycerts:/etc/caddycerts
    networks:
      - server_network
    depends_on:
      - django
    environment:
      - ACME_AGREE
      - CADDYPATH=/etc/caddycerts
  gephi:
    networks:
      - database_network
    depends_on:
      - db
networks:
  database_network:
    driver: bridge
  server_network:
    driver: bridge
volumes:
    gunicorn-socket:
    caddycerts:
    staticfiles:
