version: "3"
services:
  db:
    restart: always
    networks:
      - database_network
  phoenix:
    restart: always
    build: ./backend
    networks:
      - database_network
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL
      - SECRET_KEY_BASE
      - PORT
      - BACKEND_HOSTNAME
  gephi:
    networks:
      - database_network
    depends_on:
      - db
networks:
  database_network:
    driver: bridge
