version: "2"

networks:
  space:
    external: false

services:
  web:
    image: ghcr.io/fediverse-space/fediverse.space:main
    restart: unless-stopped
    networks:
      - space
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - space
    volumes:
      - /var/lib/postgresql/data
