version: '3'
services:
  db:
    image: postgres
    environment:
      # Set these in .env
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    environment:
      # Set these in .env
      - SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SETTINGS_MODULE
    build: ./backend/api
    command: bash scripts/docker-entrypoint.sh
    volumes:
      - ./backend/api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
