[build]
  base = "frontend/"
  publish = "frontend/build/"

[build.environment]
  INLINE_RUNTIME_CHUNK = "false"

[context.develop.environment]
  REACT_APP_STAGING = "true"

[context.branch-deploy.environment]
  REACT_APP_STAGING = "true"

[context.deploy-preview.environment]
  REACT_APP_STAGING = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1"
  Content-Security-Policy = "default-src 'self' https://*.fediverse.space; style-src 'self' 'unsafe-inline'; script-src 'self' https://*.fediverse.space https://plausible.cursed.technology"

