[build]
  base = "frontend/"
  publish = "frontend/build/"

[context.develop.environment]
  REACT_APP_STAGING = "true"

[context.branch-deploy.environment]
  REACT_APP_STAGING = "true"

[context.deploy-preview.environment]
  REACT_APP_STAGING = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

